### ISSUE TITLE
Running cargo compile command in readme fails.

### ISSUE THREAD

**Issue by PrestonLaw** [PonasKovas/rotmguard#2]
I am getting two errors, pasted below from compiler output to terminal:

```
error[E0432]: unresolved import `std::num::NonZero`
  --> src/module/autonexus/projectiles.rs:11:34
   |
11 | use std::{collections::BTreeMap, num::NonZero};
   |                                  ^^^^^-------
   |                                  |    |
   |                                  |    help: a similar name exists in the module: `NonZeroI8`
   |                                  no `NonZero` in `num`

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:1:12
  |
1 | #![feature(noop_waker)]
  |            ^^^^^^^^^^
```

I don't know the Rust language, but I'll try to help as best I can.

I am running Ubuntu 22.04.  As far as I can tell, I followed the instructions in the readme precisely.  I did not have `cargo` installed before I found this repository, so I installed it through apt.  I did have `iptables` installed.  Please feel free to ask if there is more data you want me to supply on my system, or if you want to know the settings I put in the downloaded config file.

**Comment by PonasKovas** [comment]
Hi, you need to use the nightly rust version.

1. Install rust via rustup, not cargo directly (you will probably need to remove cargo first due to conflicts)
2. `rustup install nightly`
3. `rustup default nightly`
4. And then try again "cargo build -r"

**Comment by PrestonLaw** [comment]
Hi,

I ran `sudo apt remove cargo`, installed `rustup` with the command `sudo snap install rustup --classic` after an attempt without the `--classic` flag instructed me to add it, had no problems with commands 2 and 3 on your list, but now `cargo build -r` gives me the error `bash: /usr/bin/cargo: No such file or directory`, and reinstalling `cargo` with apt gives the same errors as before.

Again, I do not know the Rust language; I have not used it before at any significant scale.  Please advise.

**Comment by PonasKovas** [comment]
I have never seen anyone use rustup through snap.
Try using the command to install it thats given here:
https://www.rust-lang.org/tools/install

Don't worry I will happily help you if you still have problems, it's very
exciting to see someone wanting to use my project :)

I might also compile on my machine and upload to github releases to make it
easier for you later

**Comment by PonasKovas** [comment]
https://github.com/PonasKovas/rotmguard/releases/tag/0.1.0

Here you can try downloading this, and you won't need to compile anything or have rust installed.

Make sure to have the `rotmguard.toml` config in your working directory when running it

**Comment by PonasKovas** [comment]
If you get it working I'd love to hear your opinion about this tool!

**Comment by PrestonLaw** [comment]
I got it working.  Downloading from release worked like a charm!

Two quick notes that I feel you should consider editing the readme to address:

First, the path to assets_res cannot use `~/`; it has to be `/home/<username>/`, and similarly, the `C:` path mentioned has a folder name of `drive_c/`.  The full line in my config file (personal data removed) is thus `assets_res = "/home/<username>/.steam/root/steamapps/compatdata/<steam-game-id>/pfx/drive_c/users/steamuser/Documents/RealmOfTheMadGod/Production/RotMG Exalt_Data/resources.assets"`.

Second, updating the hp value to autonexus at in-game does not update the value stored in the .toml file.

My opinion on the tool is very positive.  I only went looking for a tool like this because I wanted autonexus, however; I got really freaking sick of re-leveling and re-running sprite worlds every time I decided to look at a dungeon I hadn't done before and I ran into an unfamiliar pattern.  I now have the second 7/8 character I've ever managed to get, which is very gratifying.  I ended up disabling the anti-debuff portion of the tool off, because I don't want to go overboard with the cheats - my personal opinion is that autonexus doesn't excessively trivialize the game or marginalize my ability to play bullet-hell.

Your next goal with this project, if you want one, should definitely involve automatic use of health potions in quick-consumable slots or in inventory when health drops under a specified value - I'll be setting mine to half-health, if that ever happens.

I discovered this off Reddit, so I'll be PMing your username there shortly in case you want to ask me for more specific feedback and not have it immortalized on Github.  Thank you for this wonderful tool!

**Comment by PonasKovas** [comment]
Glad to hear that you like it!

>  the path to assets_res cannot use ~/

It can, but it will be the root home, because you are running `rotmguard` with sudo.

> updating the hp value to autonexus at in-game does not update the value stored in the .toml file.

This is intentional. The config file is like persistent settings, and the command is for changing it quickly in real time. For any persistent changes you need to edit the config.

> automatic use of health potions in quick-consumable slots or in inventory when health drops

Unfortunately I have quit rotmg :joy_cat: so I won't be developing this tool further, but I can accept PRs.

Congrats on your 7/8! I understand disabling anti debuffs, but also I would like to recommend fake slow to you. Especially in endgame dungeons like moonlight village or king patience it is extremely helpful, and IMO it should be added to official game because it's just stupid trying to dodge with 75 speed especially if your framerate isnt that good or you have input lag.
